### ISSUE TITLE
Generated JAR problem

### ISSUE THREAD

**Issue by paulo-coutinho** [Snapchat/djinni#39]
Hi,

The generated JAR from command `bazel build //src:djinni` is throwing error when it is executed.

Command:
`java -jar bazel-bin/src/djinni.jar`

Error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/runtime/NonLocalReturnControl$mcV$sp
	at djinni.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.runtime.NonLocalReturnControl$mcV$sp
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

I think that not all classes or dependencies are inside the JAR.

Can anyone help me?

**Comment by paulo-coutinho** [comment]
Hi,

I solved here:
https://github.com/Snapchat/djinni/pull/38/commits/5be2c95d27e70966dcc373934426e07db0a5b65a
